---
engines:
  eslint:
    enabled: true
    config:
      extensions:
      - .js
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
          mass_threshold: 60

ratings:
  paths:
  - app/**.js
exclude_paths:
- "test/"
- "docs/"
- "tasks/"
- "devtools/"
- "node_modules/"
- "build/"
- "app/core/routers/"
- "app/audit/routers/"
- "app/core/entities/"
- "app/audit/entities/"